export const GET_DATA_HOME = 'GET_DATA_HOME';
export const GET_DATA_HOME_SUCCESS = 'GET_DATA_HOME_SUCCESS';
export const GET_DATA_HOME_FAILUSE = 'GET_DATA_HOME_FAILUSE';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_DATA_CATEGORY_SUCCESS = 'GET_DATA_CATEGORY_SUCCESS';
export const GET_DATA_CATEGORY_FAILUSE = 'GET_DATA_CATEGORY_FAILUSE';
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY';
export const GET_DATA_SUB_CATEGORY_SUCCESS = 'GET_DATA_SUB_CATEGORY_SUCCESS';
export const GET_DATA_SUB_CATEGORY_FAILUSE = 'GET_DATA_SUB_CATEGORY_FAILUSE';
export const GET_AUTHOR = 'GET_AUTHOR';
export const GET_DATA_AUTHOR_SUCCESS = 'GET_DATA_AUTHOR_SUCCESS';
export const GET_DATA_AUTHOR_FAILUSE = 'GET_DATA_AUTHOR_FAILUSE';
export const GET_AUTHORLIST = 'GET_AUTHORLIST';
export const GET_DATA_AUTHORLIST_SUCCESS = 'GET_DATA_AUTHORLIST_SUCCESS';
export const GET_DATA_AUTHORLIST_FAILUSE = 'GET_DATA_AUTHORLIST_FAILUSE';
export const GET_LATEST = 'GET_LATEST';
export const GET_DATA_LATEST_SUCCESS = 'GET_DATA_LATEST_SUCCESS';
export const GET_DATA_LATEST_FAILUSE = 'GET_DATA_LATEST_FAILUSE';
export const GET_DATA_DETAIL = 'GET_DATA_DETAIL';
export const GET_DATA_DETAIL_SUCCESS = 'GET_DATA_DETAIL_SUCCESS';
export const GET_DATA_DETAIL_FAILUSE = 'GET_DATA_DETAIL_FAILUSE';
export const GET_DATA_SEARCH = 'GET_DATA_SEARCH';
export const GET_DATA_SEARCH_SUCCESS = 'GET_DATA_SEARCH_SUCCESS';
export const GET_DATA_SEARCH_FAILUSE = 'GET_DATA_SEARCH_FAILUSE';




