export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const FETCH_PRODUCTS_NEWS = 'FETCH_PRODUCTS_NEWS';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const USER_PROFILE='USER_PROFILE';

//items
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_TO_CART = "REMOVE_PRODUCT_TO_CART";
export const INCR_QUANTITY = "INCR_QUANTITY";
export const DECR_QUANTITY = "DECR_QUANTITY";
export const TOTAL_MONEY = "TOTAL_MONEY";
export const GET_CART = "GET_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
//map
export const FETCHING_MAP = "FETCHING_MAP";
export const FETCHING_MAP_SUCCESS = "FETCHING_MAP_SUCCESS";
export const FETCHING_MAP_FAILURE = "FETCHING_MAP_FAILURE";
