export const GET_DATA_HOME = 'GET_DATA_HOME';
export const GET_DATA_HOME_SUCCESS = 'GET_DATA_HOME_SUCCESS';
export const GET_DATA_HOME_FAILUSE = 'GET_DATA_HOME_FAILUSE';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_DATA_CATEGORY_SUCCESS = 'GET_DATA_CATEGORY_SUCCESS';
export const GET_DATA_CATEGORY_FAILUSE = 'GET_DATA_CATEGORY_FAILUSE';
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY';
export const GET_DATA_SUB_CATEGORY_SUCCESS = 'GET_DATA_SUB_CATEGORY_SUCCESS';
export const GET_DATA_SUB_CATEGORY_FAILUSE = 'GET_DATA_SUB_CATEGORY_FAILUSE';
export const GET_AUTHOR = 'GET_AUTHOR';
export const GET_DATA_AUTHOR_SUCCESS = 'GET_DATA_AUTHOR_SUCCESS';
export const GET_DATA_AUTHOR_FAILUSE = 'GET_DATA_AUTHOR_FAILUSE';
export const GET_AUTHORLIST = 'GET_AUTHORLIST';
export const GET_DATA_AUTHORLIST_SUCCESS = 'GET_DATA_AUTHORLIST_SUCCESS';
export const GET_DATA_AUTHORLIST_FAILUSE = 'GET_DATA_AUTHORLIST_FAILUSE';
export const GET_LATEST = 'GET_LATEST';
export const GET_DATA_LATEST_SUCCESS = 'GET_DATA_LATEST_SUCCESS';
export const GET_DATA_LATEST_FAILUSE = 'GET_DATA_LATEST_FAILUSE';
export const GET_DATA_DETAIL = 'GET_DATA_DETAIL';
export const GET_DATA_DETAIL_SUCCESS = 'GET_DATA_DETAIL_SUCCESS';
export const GET_DATA_DETAIL_FAILUSE = 'GET_DATA_DETAIL_FAILUSE';

export const GET_DATA_COMMENT = 'GET_DATA_COMMENT';
export const GET_DATA_COMMENT_SUCCESS = 'GET_DATA_COMMENT_SUCCESS';
export const GET_DATA_COMMENT_FAILUSE = 'GET_DATA_COMMENT_FAILUSE';

export const GET_DATA_RATE = 'GET_DATA_RATE';
export const GET_DATA_RATE_SUCCESS = 'GET_DATA_RATE_SUCCESS';
export const GET_DATA_RATE_FAILUSE = 'GET_DATA_RATE_FAILUSE';

export const GET_DATA_SEARCH = 'GET_DATA_SEARCH';
export const GET_DATA_SEARCH_SUCCESS = 'GET_DATA_SEARCH_SUCCESS';
export const GET_DATA_SEARCH_FAILUSE = 'GET_DATA_SEARCH_FAILUSE';

export const GET_LANGUAGE = 'GET_LANGUAGE';
export const LANGUAGE = 'LANGUAGE';
export const SWITCH = 'SWITCH';

export const CHECK_LOGIN = 'CHECK_LOGIN';

export const GET_FAVORITE_SUCCESS = 'GET_FAVORITE_SUCCESS';
export const ADD_TO_FAVORITE_SUCCESS = 'ADD_TO_FAVORITE_SUCCESS';
export const REMOVE_FROM_FAVORITE_SUCCESS = 'REMOVE_FROM_FAVORITE_SUCCESS';


export const GET_DOWNLOAD_SUCCESS = 'GET_DOWNLOAD_SUCCESS';
export const ADD_TO_DOWNLOAD_SUCCESS = 'ADD_TO_DOWNLOAD_SUCCESS';
export const REMOVE_FROM_DOWNLOAD_SUCCESS = 'REMOVE_FROM_DOWNLOAD_SUCCESS';
